#!/bin/bash

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
mkdir -p ~/.config/tmux
touch ~/.config/tmux/tmux.conf

echo "Remember to do <leader> <Shift + i> to install the config file stuff"


#read -p "Enter some random value: " TEST
